version: '3.8'
services:
  backend-software2:
    container_name: backend-software2
    build:
      context: ./backend-software2
      dockerfile: dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./backend-software2:/app
    depends_on:
      - mongodb
      - mysql
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_USER=duodinamico
      - MONGO_PASSWORD=1310
      - MONGO_DATABASE=hotels
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1310
      - MYSQL_DATABASE=hotels
    networks:
      - software2
  frontend-software2:
    container_name: frontend-software2
    build:
      context: ./frontend-software2
      dockerfile: dockerfile
    ports:
      - 8080:80
    volumes:
      - ./frontend-software2:/app
    depends_on:
      - backend-software2
    networks:
      - software2
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=duodinamico
      - MONGO_INITDB_ROOT_PASSWORD=1310
    volumes:
      -mongo_data:/data/db
    networks:
      - software2
  mysql:
    container_name: mysql
    image: mysql:8.4.4
    ports:
    - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1310
      - MYSQL_DATABASE=hotels
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - software2

volumes:
  mongo_data:
  mysql_data:

networks:
  software2: