version: '3.8'

services:
  backend-hotels:
    container_name: backend-hotels
    build:
      context: ./backend-software2/hotels
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    volumes:
      - ./backend-software2/hotels:/app
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_USER=duodinamico
      - MONGO_PASSWORD=1310
      - MONGO_DATABASE=hotels
    networks:
      - software2

  backend-users:
    container_name: backend-users
    build:
      context: ./backend-software2/users
      dockerfile: Dockerfile
    ports:
      - 3002:3000
    volumes:
      - ./backend-software2/users:/app
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_USER=duodinamico
      - MONGO_PASSWORD=1310
      - MONGO_DATABASE=users
    networks:
      - software2

  frontend-software2:
    container_name: frontend-software2
    build:
      context: ./frontend-software2
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    volumes:
      - ./frontend-software2:/app
      - /app/node_modules
    depends_on:
      - backend-hotels
      - backend-users
    networks:
      - software2

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=duodinamico
      - MONGO_INITDB_ROOT_PASSWORD=1310
    networks:
      - software2
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

networks:
  software2: