FROM node:23.11-slim as build
RUN npm install -g @angular/cli
WORKDIR /app
COPY frontend-software2/package*.json ./
RUN npm install
COPY frontend-software2/ .
RUN ng build --configuration=production
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
